# Generated by Django 5.0.6 on 2024-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_useraccounts_is_emp_alter_useraccounts_is_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="useraccounts",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="useraccounts",
            name="is_emp",
        ),
        migrations.RemoveField(
            model_name="useraccounts",
            name="is_manager",
        ),
        migrations.AddField(
            model_name="useraccounts",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
