# Generated by Django 5.0.6 on 2024-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_remove_employee_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccounts",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("nothiredyet", "Not Hired Yet"),
                ],
                default="nothiredyet",
                max_length=50,
            ),
        ),
    ]
