# Generated by Django 5.0.6 on 2024-06-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_alter_useraccounts_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="left_on",
            field=models.DateField(blank=True, null=True, verbose_name="Left On"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_status",
            field=models.CharField(
                choices=[
                    ("ApplicationReceived", "Application Received"),
                    ("InterviewScheduled", "Interview Scheduled"),
                    ("Hired", "Hired"),
                    ("NotAccepted", "Not Accepted"),
                    ("left", "Left"),
                ],
                max_length=50,
                verbose_name="Employee Status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hired_on",
            field=models.DateField(blank=True, null=True, verbose_name="Hired on"),
        ),
    ]
